# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import authentication_pb2 as authentication__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in authentication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthenticatorStub(object):
    """Service used to allow users to create an account for tutor booking service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/authentication.Authenticator/RegisterUser',
                request_serializer=authentication__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=authentication__pb2.AuthenticatorReply.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/authentication.Authenticator/Login',
                request_serializer=authentication__pb2.LoginRequest.SerializeToString,
                response_deserializer=authentication__pb2.AuthenticatorReply.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/authentication.Authenticator/ValidateToken',
                request_serializer=authentication__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=authentication__pb2.ValidateTokenReply.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/authentication.Authenticator/Logout',
                request_serializer=authentication__pb2.LogoutRequest.SerializeToString,
                response_deserializer=authentication__pb2.LogoutReply.FromString,
                _registered_method=True)
        self.ListAllUsers = channel.unary_unary(
                '/authentication.Authenticator/ListAllUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=authentication__pb2.ListAllUsersReply.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/authentication.Authenticator/GetUser',
                request_serializer=authentication__pb2.GetUserRequest.SerializeToString,
                response_deserializer=authentication__pb2.GetUserReply.FromString,
                _registered_method=True)


class AuthenticatorServicer(object):
    """Service used to allow users to create an account for tutor booking service
    """

    def RegisterUser(self, request, context):
        """Creates student profile from credentials
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Checks if user credentials exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Checks user username and role based on provided token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logs user our of system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllUsers(self, request, context):
        """List all current users in the system (only tutors can see)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Get user information from username
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=authentication__pb2.RegisterUserRequest.FromString,
                    response_serializer=authentication__pb2.AuthenticatorReply.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=authentication__pb2.LoginRequest.FromString,
                    response_serializer=authentication__pb2.AuthenticatorReply.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=authentication__pb2.ValidateTokenRequest.FromString,
                    response_serializer=authentication__pb2.ValidateTokenReply.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=authentication__pb2.LogoutRequest.FromString,
                    response_serializer=authentication__pb2.LogoutReply.SerializeToString,
            ),
            'ListAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=authentication__pb2.ListAllUsersReply.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=authentication__pb2.GetUserRequest.FromString,
                    response_serializer=authentication__pb2.GetUserReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authentication.Authenticator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('authentication.Authenticator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Authenticator(object):
    """Service used to allow users to create an account for tutor booking service
    """

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authentication.Authenticator/RegisterUser',
            authentication__pb2.RegisterUserRequest.SerializeToString,
            authentication__pb2.AuthenticatorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authentication.Authenticator/Login',
            authentication__pb2.LoginRequest.SerializeToString,
            authentication__pb2.AuthenticatorReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authentication.Authenticator/ValidateToken',
            authentication__pb2.ValidateTokenRequest.SerializeToString,
            authentication__pb2.ValidateTokenReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authentication.Authenticator/Logout',
            authentication__pb2.LogoutRequest.SerializeToString,
            authentication__pb2.LogoutReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authentication.Authenticator/ListAllUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            authentication__pb2.ListAllUsersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authentication.Authenticator/GetUser',
            authentication__pb2.GetUserRequest.SerializeToString,
            authentication__pb2.GetUserReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
