# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import availability_pb2 as availability__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in availability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SetAvailabilityStub(object):
    """Service allows tutors to set their availabile times
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTimeSlot = channel.unary_unary(
                '/availability.SetAvailability/AddTimeSlot',
                request_serializer=availability__pb2.AddTimeSlotRequest.SerializeToString,
                response_deserializer=availability__pb2.SlotAvailabilityReply.FromString,
                _registered_method=True)
        self.RemoveTimeSlot = channel.unary_unary(
                '/availability.SetAvailability/RemoveTimeSlot',
                request_serializer=availability__pb2.RemoveTimeSlotRequest.SerializeToString,
                response_deserializer=availability__pb2.SlotAvailabilityReply.FromString,
                _registered_method=True)
        self.ListAllTutorsWithTimeSlots = channel.unary_unary(
                '/availability.SetAvailability/ListAllTutorsWithTimeSlots',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=availability__pb2.ListAllTutorsWithTimeSlotsReply.FromString,
                _registered_method=True)
        self.ListAllTimeSlots = channel.unary_unary(
                '/availability.SetAvailability/ListAllTimeSlots',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=availability__pb2.ListTimeSlotsReply.FromString,
                _registered_method=True)
        self.ListTutorTimeSlots = channel.unary_unary(
                '/availability.SetAvailability/ListTutorTimeSlots',
                request_serializer=availability__pb2.ListTutorTimeSlotsRequest.SerializeToString,
                response_deserializer=availability__pb2.ListTimeSlotsReply.FromString,
                _registered_method=True)
        self.UpdateTimeSlotStatus = channel.unary_unary(
                '/availability.SetAvailability/UpdateTimeSlotStatus',
                request_serializer=availability__pb2.UpdateTimeSlotStatusRequest.SerializeToString,
                response_deserializer=availability__pb2.UpdateTimeSlotStatusReply.FromString,
                _registered_method=True)
        self.GetSlot = channel.unary_unary(
                '/availability.SetAvailability/GetSlot',
                request_serializer=availability__pb2.GetSlotRequest.SerializeToString,
                response_deserializer=availability__pb2.GetSlotReply.FromString,
                _registered_method=True)


class SetAvailabilityServicer(object):
    """Service allows tutors to set their availabile times
    """

    def AddTimeSlot(self, request, context):
        """Tutors add availability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTimeSlot(self, request, context):
        """Tutors remove availability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllTutorsWithTimeSlots(self, request, context):
        """List all tutors that have available time slots
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllTimeSlots(self, request, context):
        """List every time slot available
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTutorTimeSlots(self, request, context):
        """List all slots that are currently open for a particular tutor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTimeSlotStatus(self, request, context):
        """Update booked status based on create (booking) service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSlot(self, request, context):
        """Obtain time slot for specified slot id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SetAvailabilityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTimeSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTimeSlot,
                    request_deserializer=availability__pb2.AddTimeSlotRequest.FromString,
                    response_serializer=availability__pb2.SlotAvailabilityReply.SerializeToString,
            ),
            'RemoveTimeSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTimeSlot,
                    request_deserializer=availability__pb2.RemoveTimeSlotRequest.FromString,
                    response_serializer=availability__pb2.SlotAvailabilityReply.SerializeToString,
            ),
            'ListAllTutorsWithTimeSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllTutorsWithTimeSlots,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=availability__pb2.ListAllTutorsWithTimeSlotsReply.SerializeToString,
            ),
            'ListAllTimeSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllTimeSlots,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=availability__pb2.ListTimeSlotsReply.SerializeToString,
            ),
            'ListTutorTimeSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTutorTimeSlots,
                    request_deserializer=availability__pb2.ListTutorTimeSlotsRequest.FromString,
                    response_serializer=availability__pb2.ListTimeSlotsReply.SerializeToString,
            ),
            'UpdateTimeSlotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTimeSlotStatus,
                    request_deserializer=availability__pb2.UpdateTimeSlotStatusRequest.FromString,
                    response_serializer=availability__pb2.UpdateTimeSlotStatusReply.SerializeToString,
            ),
            'GetSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSlot,
                    request_deserializer=availability__pb2.GetSlotRequest.FromString,
                    response_serializer=availability__pb2.GetSlotReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'availability.SetAvailability', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('availability.SetAvailability', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SetAvailability(object):
    """Service allows tutors to set their availabile times
    """

    @staticmethod
    def AddTimeSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/availability.SetAvailability/AddTimeSlot',
            availability__pb2.AddTimeSlotRequest.SerializeToString,
            availability__pb2.SlotAvailabilityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTimeSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/availability.SetAvailability/RemoveTimeSlot',
            availability__pb2.RemoveTimeSlotRequest.SerializeToString,
            availability__pb2.SlotAvailabilityReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllTutorsWithTimeSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/availability.SetAvailability/ListAllTutorsWithTimeSlots',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            availability__pb2.ListAllTutorsWithTimeSlotsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllTimeSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/availability.SetAvailability/ListAllTimeSlots',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            availability__pb2.ListTimeSlotsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTutorTimeSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/availability.SetAvailability/ListTutorTimeSlots',
            availability__pb2.ListTutorTimeSlotsRequest.SerializeToString,
            availability__pb2.ListTimeSlotsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTimeSlotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/availability.SetAvailability/UpdateTimeSlotStatus',
            availability__pb2.UpdateTimeSlotStatusRequest.SerializeToString,
            availability__pb2.UpdateTimeSlotStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/availability.SetAvailability/GetSlot',
            availability__pb2.GetSlotRequest.SerializeToString,
            availability__pb2.GetSlotReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
