# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: create.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'create.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63reate.proto\x12\x06\x63reate\"R\n\x18\x43reateAppointmentRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07slot_id\x18\x02 \x01(\x03\x12\x16\n\x0etutor_username\x18\x03 \x01(\t\"\xb7\x01\n\x13\x41ppointmentResponse\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x18\n\x10student_username\x18\x02 \x01(\t\x12\x16\n\x0etutor_username\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x0f\n\x07slot_id\x18\x07 \x01(\x03\x12\x0f\n\x07message\x18\x08 \x01(\t2n\n\x18\x43reateAppointmentService\x12R\n\x11\x43reateAppointment\x12 .create.CreateAppointmentRequest\x1a\x1b.create.AppointmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'create_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEAPPOINTMENTREQUEST']._serialized_start=24
  _globals['_CREATEAPPOINTMENTREQUEST']._serialized_end=106
  _globals['_APPOINTMENTRESPONSE']._serialized_start=109
  _globals['_APPOINTMENTRESPONSE']._serialized_end=292
  _globals['_CREATEAPPOINTMENTSERVICE']._serialized_start=294
  _globals['_CREATEAPPOINTMENTSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
