# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modify.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'modify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmodify.proto\x12\x06modify\"2\n\x18\x43\x61ncelAppointmentRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\"\\\n\x18\x43hangeAppointmentRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x13\n\x0bold_slot_id\x18\x02 \x01(\x03\x12\x13\n\x0bnew_slot_id\x18\x03 \x01(\x03\"/\n\x15GetAppointmentRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\"\xb7\x01\n\x13\x41ppointmentResponse\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x18\n\x10student_username\x18\x02 \x01(\t\x12\x16\n\x0etutor_username\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x0f\n\x07message\x18\x07 \x01(\t\x12\x0f\n\x07slot_id\x18\x08 \x01(\x03\x32\x90\x02\n\x18ModifyAppointmentService\x12R\n\x11\x43\x61ncelAppointment\x12 .modify.CancelAppointmentRequest\x1a\x1b.modify.AppointmentResponse\x12R\n\x11\x43hangeAppointment\x12 .modify.ChangeAppointmentRequest\x1a\x1b.modify.AppointmentResponse\x12L\n\x0eGetAppointment\x12\x1d.modify.GetAppointmentRequest\x1a\x1b.modify.AppointmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANCELAPPOINTMENTREQUEST']._serialized_start=24
  _globals['_CANCELAPPOINTMENTREQUEST']._serialized_end=74
  _globals['_CHANGEAPPOINTMENTREQUEST']._serialized_start=76
  _globals['_CHANGEAPPOINTMENTREQUEST']._serialized_end=168
  _globals['_GETAPPOINTMENTREQUEST']._serialized_start=170
  _globals['_GETAPPOINTMENTREQUEST']._serialized_end=217
  _globals['_APPOINTMENTRESPONSE']._serialized_start=220
  _globals['_APPOINTMENTRESPONSE']._serialized_end=403
  _globals['_MODIFYAPPOINTMENTSERVICE']._serialized_start=406
  _globals['_MODIFYAPPOINTMENTSERVICE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
