# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import modify_pb2 as modify__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in modify_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModifyAppointmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CancelAppointment = channel.unary_unary(
                '/modify.ModifyAppointmentService/CancelAppointment',
                request_serializer=modify__pb2.CancelAppointmentRequest.SerializeToString,
                response_deserializer=modify__pb2.AppointmentResponse.FromString,
                _registered_method=True)
        self.ChangeAppointment = channel.unary_unary(
                '/modify.ModifyAppointmentService/ChangeAppointment',
                request_serializer=modify__pb2.ChangeAppointmentRequest.SerializeToString,
                response_deserializer=modify__pb2.AppointmentResponse.FromString,
                _registered_method=True)
        self.GetAppointment = channel.unary_unary(
                '/modify.ModifyAppointmentService/GetAppointment',
                request_serializer=modify__pb2.GetAppointmentRequest.SerializeToString,
                response_deserializer=modify__pb2.AppointmentResponse.FromString,
                _registered_method=True)


class ModifyAppointmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CancelAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModifyAppointmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CancelAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAppointment,
                    request_deserializer=modify__pb2.CancelAppointmentRequest.FromString,
                    response_serializer=modify__pb2.AppointmentResponse.SerializeToString,
            ),
            'ChangeAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAppointment,
                    request_deserializer=modify__pb2.ChangeAppointmentRequest.FromString,
                    response_serializer=modify__pb2.AppointmentResponse.SerializeToString,
            ),
            'GetAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppointment,
                    request_deserializer=modify__pb2.GetAppointmentRequest.FromString,
                    response_serializer=modify__pb2.AppointmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modify.ModifyAppointmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modify.ModifyAppointmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModifyAppointmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CancelAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modify.ModifyAppointmentService/CancelAppointment',
            modify__pb2.CancelAppointmentRequest.SerializeToString,
            modify__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modify.ModifyAppointmentService/ChangeAppointment',
            modify__pb2.ChangeAppointmentRequest.SerializeToString,
            modify__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modify.ModifyAppointmentService/GetAppointment',
            modify__pb2.GetAppointmentRequest.SerializeToString,
            modify__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
