# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rating_pb2 as rating__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rating_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RatingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRating = channel.unary_unary(
                '/rating.RatingService/SubmitRating',
                request_serializer=rating__pb2.SubmitRatingRequest.SerializeToString,
                response_deserializer=rating__pb2.SubmitRatingResponse.FromString,
                _registered_method=True)
        self.GetTutorRatingSummary = channel.unary_unary(
                '/rating.RatingService/GetTutorRatingSummary',
                request_serializer=rating__pb2.TutorRequest.SerializeToString,
                response_deserializer=rating__pb2.TutorRatingSummary.FromString,
                _registered_method=True)
        self.GetTutorRatings = channel.unary_unary(
                '/rating.RatingService/GetTutorRatings',
                request_serializer=rating__pb2.TutorRequest.SerializeToString,
                response_deserializer=rating__pb2.TutorRatingsResponse.FromString,
                _registered_method=True)


class RatingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTutorRatingSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTutorRatings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRating': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRating,
                    request_deserializer=rating__pb2.SubmitRatingRequest.FromString,
                    response_serializer=rating__pb2.SubmitRatingResponse.SerializeToString,
            ),
            'GetTutorRatingSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTutorRatingSummary,
                    request_deserializer=rating__pb2.TutorRequest.FromString,
                    response_serializer=rating__pb2.TutorRatingSummary.SerializeToString,
            ),
            'GetTutorRatings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTutorRatings,
                    request_deserializer=rating__pb2.TutorRequest.FromString,
                    response_serializer=rating__pb2.TutorRatingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rating.RatingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rating.RatingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RatingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rating.RatingService/SubmitRating',
            rating__pb2.SubmitRatingRequest.SerializeToString,
            rating__pb2.SubmitRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTutorRatingSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rating.RatingService/GetTutorRatingSummary',
            rating__pb2.TutorRequest.SerializeToString,
            rating__pb2.TutorRatingSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTutorRatings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rating.RatingService/GetTutorRatings',
            rating__pb2.TutorRequest.SerializeToString,
            rating__pb2.TutorRatingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
