# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rating.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rating.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crating.proto\x12\x06rating\"\x93\x01\n\x13SubmitRatingRequest\x12\x18\n\x10student_username\x18\x01 \x01(\t\x12\x16\n\x0etutor_username\x18\x02 \x01(\t\x12\x16\n\x0e\x61ppointment_id\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"3\n\x14SubmitRatingResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x0cTutorRequest\x12\x16\n\x0etutor_username\x18\x01 \x01(\t\"w\n\x12TutorRatingSummary\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0etutor_username\x18\x03 \x01(\t\x12\x16\n\x0e\x61verage_rating\x18\x04 \x01(\x01\x12\x14\n\x0crating_count\x18\x05 \x01(\x05\"w\n\x0fTutorRatingItem\x12\x18\n\x10student_username\x18\x01 \x01(\t\x12\x16\n\x0e\x61ppointment_id\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"[\n\x14TutorRatingsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x05items\x18\x03 \x03(\x0b\x32\x17.rating.TutorRatingItem2\xec\x01\n\rRatingService\x12I\n\x0cSubmitRating\x12\x1b.rating.SubmitRatingRequest\x1a\x1c.rating.SubmitRatingResponse\x12I\n\x15GetTutorRatingSummary\x12\x14.rating.TutorRequest\x1a\x1a.rating.TutorRatingSummary\x12\x45\n\x0fGetTutorRatings\x12\x14.rating.TutorRequest\x1a\x1c.rating.TutorRatingsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rating_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITRATINGREQUEST']._serialized_start=25
  _globals['_SUBMITRATINGREQUEST']._serialized_end=172
  _globals['_SUBMITRATINGRESPONSE']._serialized_start=174
  _globals['_SUBMITRATINGRESPONSE']._serialized_end=225
  _globals['_TUTORREQUEST']._serialized_start=227
  _globals['_TUTORREQUEST']._serialized_end=265
  _globals['_TUTORRATINGSUMMARY']._serialized_start=267
  _globals['_TUTORRATINGSUMMARY']._serialized_end=386
  _globals['_TUTORRATINGITEM']._serialized_start=388
  _globals['_TUTORRATINGITEM']._serialized_end=507
  _globals['_TUTORRATINGSRESPONSE']._serialized_start=509
  _globals['_TUTORRATINGSRESPONSE']._serialized_end=600
  _globals['_RATINGSERVICE']._serialized_start=603
  _globals['_RATINGSERVICE']._serialized_end=839
# @@protoc_insertion_point(module_scope)
